# Generated by Django 4.2 on 2026-03-10 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id_datosmoto', models.AutoField(db_column='ID_DATOSMOTO', primary_key=True, serialize=False)),
                ('marca_moto', models.CharField(db_column='MARCA_MOTO', max_length=25)),
                ('modelo_moto', models.CharField(db_column='MODELO_MOTO', max_length=50)),
                ('color_moto', models.CharField(db_column='COLOR_MOTO', max_length=30)),
                ('imagen_moto', models.ImageField(blank=True, db_column='IMAGEN_MOTO', null=True, upload_to='motos/')),
                ('soat_moto', models.DateField(db_column='SOAT_MOTO')),
                ('tecnomecanica', models.DateField(db_column='TECNOMECANICA')),
                ('placa_moto', models.CharField(db_column='PLACA_MOTO', max_length=45)),
                ('kilometraje', models.IntegerField(db_column='KILOMETRAJE')),
                ('usuario', models.ForeignKey(db_column='usuario_ID_USUARIO', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'datos_moto',
            },
        ),
    ]
