# Generated by Django 4.2 on 2026-03-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='cilindraje',
            field=models.IntegerField(db_column='CILINDRAJE', default=150),
        ),
        migrations.AddField(
            model_name='moto',
            name='fecha_ultimo_mantenimiento',
            field=models.DateField(blank=True, db_column='FECHA_ULTIMO_MANT', null=True),
        ),
        migrations.AddField(
            model_name='moto',
            name='tipo_aceite',
            field=models.CharField(choices=[('MINERAL', 'Mineral'), ('SEMISINTETICO', 'Semisintético'), ('SINTETICO', 'Sintético')], db_column='TIPO_ACEITE', default='SEMISINTETICO', max_length=15),
        ),
        migrations.AddField(
            model_name='moto',
            name='tipo_uso',
            field=models.CharField(choices=[('URBANO', 'Urbano (Trabajo/Ciudad)'), ('MIXTO', 'Mixto (Ciudad y Carretera)'), ('TURISMO', 'Turismo (Viajes largos)')], db_column='TIPO_USO', default='MIXTO', max_length=15),
        ),
    ]
