# Generated by Django 4.2 on 2026-03-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0002_moto_cilindraje_moto_fecha_ultimo_mantenimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='km_ultimo_mantenimiento',
            field=models.IntegerField(db_column='KM_ULTIMO_MANT', default=0),
        ),
    ]
