server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # --- BLOQUE CRÍTICO PARA ANGULAR ---
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy para el Backend (Django/Gunicorn)
    location /api/ {
        proxy_pass http://roarmot_backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Manejo de archivos estáticos/media (Fotos de motos/productos)
    location /media/ {
        # Asegúrate de que en docker-compose el volumen apunte a esta ruta
        alias /usr/share/nginx/html/media/;
        expires 30d;
        add_header Cache-Control "public";
    }

    # Manejo de errores de servidor
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}