version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: roarmot_db
    restart: always
    environment:
      MYSQL_DATABASE: roarmot_db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    healthcheck:
      # Este comando es el que le da permiso al backend de iniciar
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s # Un poco más de tiempo entre chequeos para no saturar
      timeout: 5s
      retries: 10 # Más intentos por si MySQL demora en iniciar sus procesos internos

  backend:
    build: ./backend
    container_name: roarmot_backend
    restart: always
    # AGREGAMOS ESTO: Sobrescribimos el comando para aumentar el tiempo de espera (Timeout)
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120
    volumes:
      - ./media:/app/media
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=roarmot_db
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_HOST=db
      - TZ=America/Bogota
    depends_on:
      db:
        condition: service_healthy
    # Agregamos un healthcheck al backend para que el frontend espere
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/index/"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: roarmot_frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./media:/usr/share/nginx/html/media:ro
    depends_on:
      backend:
        condition: service_healthy # Ahora el frontend espera a que el backend responda

volumes:
  # Cambiamos esto para usar la ruta física que ya tiene permisos
  db_data: