version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: roarmot_db
    restart: always
    environment:
      MYSQL_DATABASE: roarmot_db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: roarmot_backend
    restart: always
    # Eliminamos 'command' de aquí porque ya está definido en el Dockerfile con Gunicorn
    volumes:
      - ./media:/app/media  # Importante para que las fotos de motos persistan
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=roarmot_db
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_HOST=db
      - TZ=America/Bogota # Para que las alertas de mantenimiento sean precisas
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: roarmot_frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      # AGREGA ESTA LÍNEA: Conecta las fotos del backend con el servidor Nginx
      - ./media:/usr/share/nginx/html/media:ro
    # En producción NO usamos volumes para el frontend, el build ya está en la imagen de Nginx
    depends_on:
      - backend

volumes:
  db_data: