# Generated by Django 4.2 on 2026-03-13 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('es_por_fecha', models.BooleanField(default=False)),
                ('es_por_km', models.BooleanField(default=True)),
                ('intervalo_km', models.IntegerField(blank=True, null=True)),
                ('intervalo_meses', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMantenimiento',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_realizado', models.DateField()),
                ('km_realizado', models.IntegerField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='motos.moto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimientos.tipomantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='GestorAlerta',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('nivel_prioridad', models.CharField(default='normal', max_length=20)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motos.moto')),
            ],
        ),
    ]
