# Generated by Django 4.2 on 2026-03-31 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestoralerta',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
