# Generated by Django 4.2 on 2026-04-01 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0002_gestoralerta_fecha_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestoralerta',
            name='fecha_vencimiento',
        ),
    ]
