# Generated by Django 4.2 on 2026-03-18 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('sku', models.CharField(help_text='Referencia única de inventario', max_length=20, unique=True)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=3, help_text='Alerta cuando el stock sea menor a este número')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('talla', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large'), ('NA', 'No Aplica / Accesorios')], default='NA', max_length=5)),
                ('id_subcategoria', models.IntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('vendedor', models.ForeignKey(db_column='ID_USUARIO', on_delete=django.db.models.deletion.CASCADE, related_name='mis_productos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
