# Generated by Django 4.2 on 2026-04-01 23:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(help_text='Referencia única de inventario', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('sku', 'vendedor')},
        ),
    ]
