# Generated by Django 4.2 on 2026-04-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0003_remove_producto_imagen_productoimagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoimagen',
            options={'ordering': ['-es_principal', '-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='productoimagen',
            name='es_principal',
            field=models.BooleanField(default=False, help_text='Indica si esta imagen es la portada del producto'),
        ),
    ]
