# Generated by Django 4.2 on 2026-04-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0004_alter_productoimagen_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='en_oferta',
            field=models.BooleanField(default=False, help_text='Activa el modo promoción'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_fin_oferta',
            field=models.DateTimeField(blank=True, help_text='Cuándo termina la promoción', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='porcentaje_descuento',
            field=models.PositiveIntegerField(default=0, help_text='Ej: 20 para un 20% de dto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
