# Generated by Django 6.0.2 on 2026-03-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('ID_USUARIO', models.AutoField(primary_key=True, serialize=False)),
                ('TIPO_DOCUMENTO', models.CharField(blank=True, max_length=255, null=True)),
                ('NUMERO_USUARIO', models.CharField(blank=True, max_length=255, null=True)),
                ('NOMBRE_USUARIO', models.CharField(blank=True, max_length=255, null=True)),
                ('APELLIDO_USUARIO', models.CharField(blank=True, max_length=255, null=True)),
                ('TEL_USUARIO', models.CharField(blank=True, max_length=255, null=True)),
                ('CORREO_USUARIO', models.EmailField(max_length=255, unique=True)),
                ('CONTRASENA', models.CharField(max_length=255)),
                ('ESTADO_USUARIO', models.CharField(default='Activo', max_length=255)),
                ('FECHA_CREACION', models.DateTimeField(auto_now_add=True)),
                ('NOMBRE_EMPRESA', models.CharField(blank=True, max_length=255, null=True)),
                ('ROL_ID_ROL', models.IntegerField(default=1)),
                ('URL_IMAGEN_PERFIL', models.CharField(blank=True, max_length=255, null=True)),
                ('URL_IMAGEN_MOTO', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='usuario_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuario_permissions_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
