# Generated by Django 4.2 on 2026-03-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuario_options_remove_usuario_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ROL_ID_ROL',
            field=models.IntegerField(db_column='ROL_ID_ROL', default=2),
        ),
    ]
