# Generated by Django 4.2 on 2026-04-04 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usuario_rol_id_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='CIUDAD',
            field=models.CharField(blank=True, db_column='CIUDAD', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='CODIGO_POSTAL',
            field=models.CharField(blank=True, db_column='CODIGO_POSTAL', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='DEPARTAMENTO',
            field=models.CharField(blank=True, db_column='DEPARTAMENTO', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='DIRECCION_ENTREGA',
            field=models.CharField(blank=True, db_column='DIRECCION_ENTREGA', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='NOTAS_ENVIO',
            field=models.TextField(blank=True, db_column='NOTAS_ENVIO', null=True),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('id_transaccion_pasarela', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('producto_id', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='users.pedido')),
            ],
            options={
                'db_table': 'detalle_pedido',
            },
        ),
    ]
