# Generated by Django 4.2 on 2026-04-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usuario_ciudad_usuario_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='URL_IMAGEN_PERFIL',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/avatars/'),
        ),
    ]
